// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqoqaqV8P3zvTNuuwW6pwDIJa30qQsBEU',
    appId: '1:836153217143:web:f393f811f044d04fc33672',
    messagingSenderId: '836153217143',
    projectId: 'advancelogin-c5233',
    authDomain: 'advancelogin-c5233.firebaseapp.com',
    storageBucket: 'advancelogin-c5233.firebasestorage.app',
    measurementId: 'G-SGW0CXQ06N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPLME_da13w2TsUvpkRngp21eWzglNJA0',
    appId: '1:836153217143:android:e2680caa97c673a6c33672',
    messagingSenderId: '836153217143',
    projectId: 'advancelogin-c5233',
    storageBucket: 'advancelogin-c5233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAGpB3M0bF4cPiWVq-luOSoeE_RGVLMAM',
    appId: '1:836153217143:ios:512347bf75d9ebd8c33672',
    messagingSenderId: '836153217143',
    projectId: 'advancelogin-c5233',
    storageBucket: 'advancelogin-c5233.firebasestorage.app',
    iosBundleId: 'com.example.eosAdvanceLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAGpB3M0bF4cPiWVq-luOSoeE_RGVLMAM',
    appId: '1:836153217143:ios:512347bf75d9ebd8c33672',
    messagingSenderId: '836153217143',
    projectId: 'advancelogin-c5233',
    storageBucket: 'advancelogin-c5233.firebasestorage.app',
    iosBundleId: 'com.example.eosAdvanceLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqoqaqV8P3zvTNuuwW6pwDIJa30qQsBEU',
    appId: '1:836153217143:web:16c89c0930f3b52bc33672',
    messagingSenderId: '836153217143',
    projectId: 'advancelogin-c5233',
    authDomain: 'advancelogin-c5233.firebaseapp.com',
    storageBucket: 'advancelogin-c5233.firebasestorage.app',
    measurementId: 'G-PLCZ8F9R4C',
  );
}
